### ISSUE TITLE
Adding pictures to the minds.

### ISSUE THREAD

**Issue by pczachurski** [mczachurski/community-web#19]
When adding a picture and on mouse over it a lots of lines of code appearing on the screen. 
![screen01](https://cloud.githubusercontent.com/assets/11019152/6211102/7c7ea1a8-b5ce-11e4-9528-394fd29ebdc9.jpg)

**Comment by mczachurski** [comment]
Azure Storage throws exception with message: StatusMessage: "The specifed resource name contains invalid characters". 

What was the name of the file?
Can you attach this file?

**Comment by pczachurski** [comment]
I have tried with these pictures:
![screen1](https://cloud.githubusercontent.com/assets/11019152/6225576/426f9e0c-b684-11e4-92c5-9f3f32948654.jpg)

Tulips.jpg
     - Dimensions: 1024 x 768
     - Size: 606 KB
Koala.jpg
     - Dimensions: 1024 x 768
     - Size: 762 KB

And also IMG_1245.JPG
Each time was same result.

**Comment by mczachurski** [comment]
The issue was because of upper case in file name (and your user name). Azure storage accepts only names (paths) in lower case. Now it should work correctly.

**Comment by pczachurski** [comment]
It is now working correctly, but some pictures which have been uploaded before that change have disappeared.
